### ISSUE TITLE
Camera panning and player move both happens if panning key combination includes the player move key

### ISSUE THREAD

**Issue by 64kramsystem** [fishfight/punchy#61]
If a camera panning key combination (e.g. Ctrl+Up) includes a key from player move (e.g. Up), both actions will be performed.

**Comment by zicklag** [comment]
Yeah, I noticed that. I'm thinking maybe we should just change the bindings so that they don't overlap the player 2 movement.

Other alternatives would be:

- Put the camera control as a `PlayerAction` so that the `leafwing-input-manager`'s clash-detection can automatically discard the player move event when using the camera move binding.
    - Not sure we want to do this because the camera pan is really a debug feature I think, and it really isn't something a player will control normally
- Just leave it how it is because the camera panning is mostly or developers anyway it it being a little annoying to use isn't a problem.

I'm thinking changing the bindings is the simplest thing to do. Maybe to the directions on the numberpad?

**Comment by 64kramsystem** [comment]
> I'm thinking changing the bindings is the simplest thing to do. Maybe to the directions on the numberpad?

Make sense. I don't think there is any case where different bindings share any key.

**Comment by 64kramsystem** [comment]
> Maybe to the directions on the numberpad?

:thinking: My laptop doesn't have a numeric pad; at least, there's no visible marking. Not sure about other laptops!

**Comment by odecay** [comment]
Ultimately camera control should not be left to the players, it should be automatic and Controls for it removed. Right now it's in for dev purposes, but as soon as camera is implemented to satisfaction we should remove the input bindings for it.

**Comment by zicklag** [comment]
I'm working on the input mapping and it's a convenient time for removing the camera controls. Do either of you feel like it's needed anymore?

**Comment by 64kramsystem** [comment]
> I'm working on the input mapping and it's a convenient time for removing the camera controls. Do either of you feel like it's needed anymore?

I'm +1 for removal, although I've never used it in first place :smile:
